// Code generated by MockGen. DO NOT EDIT.
// Source: internal/automation/interfaces/interfaces.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	reflect "reflect"
	interfaces "tcms/m/internal/automation/interfaces"
	model "tcms/m/internal/db/model"

	gomock "github.com/golang/mock/gomock"
)

// MockTrigger is a mock of Trigger interface.
type MockTrigger struct {
	ctrl     *gomock.Controller
	recorder *MockTriggerMockRecorder
}

// MockTriggerMockRecorder is the mock recorder for MockTrigger.
type MockTriggerMockRecorder struct {
	mock *MockTrigger
}

// NewMockTrigger creates a new mock instance.
func NewMockTrigger(ctrl *gomock.Controller) *MockTrigger {
	mock := &MockTrigger{ctrl: ctrl}
	mock.recorder = &MockTriggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrigger) EXPECT() *MockTriggerMockRecorder {
	return m.recorder
}

// GetData mocks base method.
func (m *MockTrigger) GetData() map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetData")
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// GetData indicates an expected call of GetData.
func (mr *MockTriggerMockRecorder) GetData() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetData", reflect.TypeOf((*MockTrigger)(nil).GetData))
}

// GetName mocks base method.
func (m *MockTrigger) GetName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetName indicates an expected call of GetName.
func (mr *MockTriggerMockRecorder) GetName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockTrigger)(nil).GetName))
}

// MockAction is a mock of action interface.
type MockAction struct {
	ctrl     *gomock.Controller
	recorder *MockActionMockRecorder
}

// MockActionMockRecorder is the mock recorder for MockAction.
type MockActionMockRecorder struct {
	mock *MockAction
}

// NewMockAction creates a new mock instance.
func NewMockAction(ctrl *gomock.Controller) *MockAction {
	mock := &MockAction{ctrl: ctrl}
	mock.recorder = &MockActionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAction) EXPECT() *MockActionMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockAction) Execute(action model.Action, trigger interfaces.Trigger) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", action, trigger)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockActionMockRecorder) Execute(action, trigger interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockAction)(nil).Execute), action, trigger)
}

// MockCondition is a mock of condition interface.
type MockCondition struct {
	ctrl     *gomock.Controller
	recorder *MockConditionMockRecorder
}

// MockConditionMockRecorder is the mock recorder for MockCondition.
type MockConditionMockRecorder struct {
	mock *MockCondition
}

// NewMockCondition creates a new mock instance.
func NewMockCondition(ctrl *gomock.Controller) *MockCondition {
	mock := &MockCondition{ctrl: ctrl}
	mock.recorder = &MockConditionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCondition) EXPECT() *MockConditionMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockCondition) Check(trigger interfaces.Trigger) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", trigger)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Check indicates an expected call of Check.
func (mr *MockConditionMockRecorder) Check(trigger interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockCondition)(nil).Check), trigger)
}

// MockActionWithModel is a mock of ActionWithModel interface.
type MockActionWithModel struct {
	ctrl     *gomock.Controller
	recorder *MockActionWithModelMockRecorder
}

// MockActionWithModelMockRecorder is the mock recorder for MockActionWithModel.
type MockActionWithModelMockRecorder struct {
	mock *MockActionWithModel
}

// NewMockActionWithModel creates a new mock instance.
func NewMockActionWithModel(ctrl *gomock.Controller) *MockActionWithModel {
	mock := &MockActionWithModel{ctrl: ctrl}
	mock.recorder = &MockActionWithModelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActionWithModel) EXPECT() *MockActionWithModelMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockActionWithModel) Execute(trigger interfaces.Trigger) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", trigger)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockActionWithModelMockRecorder) Execute(trigger interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockActionWithModel)(nil).Execute), trigger)
}
